FROM rocker/r-ver:3.6.3
RUN apt-get update && apt-get install -y  gdal-bin git-core imagemagick libcairo2-dev libcurl4-openssl-dev libgdal-dev libgeos-dev libgeos++-dev libgit2-dev libglpk-dev libgmp-dev libicu-dev libpng-dev libproj-dev libssl-dev libudunits2-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev rclone bash &&  rm -rf /var/lib/apt/lists/*
